## Semana 3: Python for Data Science (IBM)  Chapter 5

## Profesor : Jobish Vallikavungal Devassia

## Materia   : Ciencia y analítica de datos

### Kevin Alejandro Garcia Escalante                                    A01376680


### Fecha : 4 de Octubre de 2022 

-------------------------------------------------

## Numpy 1D Arrays



##### Q1 What is the result of the following operation: np.array([1,-1])*np.array([1,1])?


In [5]:
import numpy as np

In [6]:

np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [ ]:
#RESP : array([ 1, -1])

##### Q2 What is the result of the following operation: np.dot(np.array([1,-1]),np.array([1,1]))?

In [7]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [8]:
#RESP : 0

### Lab - Working with 1D Numpy Arrays

In [9]:
# Hacer un array

array = np.array([ 1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [11]:
print("array[0]:", array[0])
print("array[1]:", array[1])
print("array[2]:", array[2])

array[0]: 1
array[1]: 2
array[2]: 3


In [13]:
print(np.__version__) # la aversion de numpy

1.21.5


In [21]:
#Slicing

# Imprimir los pares 

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])



In [22]:
print(arr[1:8:2])

[2 4 6 8]


In [23]:

# Encontrar el tamaño de la lista

In [24]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

In [25]:
b.size

b.ndim

b.shape

(7,)

In [26]:
#Encontrar la sum a de maximo y minimno valor enb un arreglo numpy 
c = np.array([-10, 201, 43, 94, 502])

In [27]:
max_c = c.max()
max_c
    
min_c = c.min()
min_c
    
    
Sum = (max_c +min_c)
Sum


492

In [29]:
#Hacer una operacion de suma entre arreglos
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])


In [30]:
arr3 = np.add(arr1, arr2)
arr3

array([30, 32, 34, 36, 38, 40])

In [31]:
#Hacer una operacion de multiplicacion de arreglos
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3, 4, 5])

In [32]:
arr3 = np.multiply(arr1, arr2)
arr3


array([ 20,  20,  60, 120, 200, 300])

In [33]:
#Hacer una operación de división de arreglos
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])


In [34]:
arr3 = np.divide(arr1, arr2)
arr3

array([ 3.33333333,  4.        ,  3.        ,  5.        , 25.        ,
        1.81818182])

## Numpy 2D Arrays

In [35]:
#Q1 How many rows are in the following numpy array?

In [37]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

In [38]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#RESP: 4

In [ ]:
#Q2 Is it possible to perform the following operation?

In [43]:
#A = np.array([[1,2],[3,4],[5,6],[7,8]])

#B = np.array([[1,2,3],[4,5,6],[7,8,9]])
#np.dot(A,B)

In [42]:
#RESP : No

### Lab - Working with 2D Numpy Arrays

In [46]:
# Crear un numpy array 2D

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [47]:
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
#Calculate size
A.size

12

In [50]:
#Acceder al elemento de la primera fila con la primera y segunda columna
A[0][0:2]

array([1, 2])

In [51]:
#Hacer un amultiplicacion de matrices
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [52]:
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

### Lab - API

In [66]:
import pandas as pd

In [60]:
# Carga data con URL
data2 = requests.get("https://www.fishwatch.gov/api/species")

In [68]:
# Recuperar resultados con json.loads()
results2 = json.loads(data2.text)


In [67]:
# Convertir json data en pandas data frame
results2 = pd.DataFrame(results2)
results2

Fishery Management  \
0    <ul>\n<li><a href="https://www.fisheries.noaa....   
1    <ul>\n<li><a href="https://www.fisheries.noaa....   
2    <ul>\n<li>\n<p><a href="https://archive.fisher...   
3    <ul>\n<li><a href="https://www.fisheries.noaa....   
4    <ul>\n<li>The states and <a href="https://www....   
..                                                 ...   
111  <ul>\n<li><a href="https://www.fisheries.noaa....   
112  <ul>\n<li><a href="https://www.greateratlantic...   
113  <ul>\n<li><a href="http://sero.nmfs.noaa.gov/"...   
114  <ul>\n<li><a href="https://sero.nmfs.noaa.gov/...   
115  <ul>\n<li>There are two stocks of Atlantic cod...   

                                               Habitat  \
0                                                 None   
1    <ul>\n<li>White hake are groundfish, meaning t...   
2    <ul>\n<li>Atlantic chub mackerel are a schooli...   
3    <ul>\n<li>Shortfin squid live in deep and shal...   
4    <ul>\n<li>American lobsters live on the ocean ...   
..                                                 ...   
111  <ul>\n<li>Younger pollock live in the mid-wate...   
112  <ul>\n<li>Monkfish live on the ocean floor, ty...   
113  <ul>\n<li>Mahi mahi live near the surface in t...   
114  <ul>\n<li>Cobia are found near structures in t...   
115  <ul>\n<li>Atlantic cod live near the ocean flo...   

                                       Habitat Impacts  \
0    Bottomfish fishing operations, typically using...   
1    Area closures and gear restrictions protect ha...   
2    Area closures and gear restrictions protect ha...   
3    Fishing gears used to harvest shortfin squid h...   
4    Fishing gears used to harvest American lobster...   
..                                                 ...   
111  The Alaska pollock fishery uses midwater trawl...   
112  Area closures and gear restrictions protect ha...   
113  Fishing gear used to catch mahi mahi rarely co...   
114  Fishing gear used to catch cobia rarely contac...   
115  Area closures and gear restrictions protect ha...   

                                         Image Gallery  \
0    [{'src': 'https://origin-east-01-drupal-fishwa...   
1    [{'src': 'https://origin-east-01-drupal-fishwa...   
2    [{'src': 'https://origin-east-01-drupal-fishwa...   
3                                                 None   
4    [{'src': 'https://origin-east-01-drupal-fishwa...   
..                                                 ...   
111  [{'src': 'https://origin-east-01-drupal-fishwa...   
112  [{'src': 'https://origin-east-01-drupal-fishwa...   
113  [{'src': 'https://origin-east-01-drupal-fishwa...   
114  [{'src': 'https://origin-east-01-drupal-fishwa...   
115  [{'src': 'https://origin-east-01-drupal-fishwa...   

                                              Location Management  \
0    <ul>\n<li>Crimson jobfish are distributed thro...       None   
1    <ul>\n<li>White hake are found in the northwes...       None   
2    <ul>\n<li>Atlantic chub mackerel in the wester...       None   
3    <ul>\n<li>Shortfin squid inhabits the continen...       None   
4    <ul>\n<li>American lobsters are found in the n...       None   
..                                                 ...        ...   
111  <ul>\n<li>Alaska pollock are found throughout ...       None   
112  <ul>\n<li>Monkfish are found in the Northwest ...       None   
113  <ul>\n<li>Mahi mahi are found in the Atlantic,...       None   
114  <ul>\n<li>In U.S. waters, cobia are most abund...       None   
115  <ul>\n<li>In the Northwest Atlantic, cod range...       None   

           NOAA Fisheries Region  \
0                Pacific Islands   
1               Greater Atlantic   
2               Greater Atlantic   
3               Greater Atlantic   
4               Greater Atlantic   
..                           ...   
111                       Alaska   
112  Greater Atlantic, Southeast   
113  Greater Atlantic, Southeast   
114  Greater Atlantic, Southeast   
115             Greater

In [69]:
#Review questions 


In [70]:
#Q1 What is the result of the following lines of code:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [ ]:
# RESP : array([0, 0, 0, 0, 0])

In [71]:
#$Q2 What is the result of the following lines of code:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)




0

In [72]:
#Q3 What is the result of the following lines of code:
a=np.array([1,1,1,1,1])

a+10




array([11, 11, 11, 11, 11])

In [ ]:
#RESP : array([11, 11, 11, 11, 11])

In [ ]:
# What is the correct code to perform matrix multiplication on the matrix A and B?:


In [73]:
np.dot(A,B)

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])